---
- name: Install Kubernetes packages
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Setup kubectl tab-completion
  shell: |
    set -o pipefail
    kubectl completion bash | tee /etc/bash_completion.d/kubectl
  args:
    executable: /bin/bash
  changed_when: false
  become: true

- name: Setup kubeadm tab-completion
  shell: |
    set -o pipefail
    kubeadm completion bash | tee /etc/bash_completion.d/kubeadm
  args:
    executable: /bin/bash
  changed_when: false
  become: true
