---
- name: Configure network
  template: 
    src: ../templates/k8s.j2
    dest: /etc/sysctl.d/k8s.conf
  
- name: Modify cgroup-driver
  template:
    src: ../templates/kubelet.j2
    dest: /etc/sysconfig/kubelet

- name: Configure docker 
  template:
    src: ../templates/daemon.j2
    dest: /etc/docker/daemon.json

- name: Confirm network changes
  command: sysctl --system

- name: Install utils and device mapper
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: Enable service kubelet and ensure it is started
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes
    state: restarted

- name: create docker service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    
- name: Restart Docker daemon
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: restarted

